### ISSUE TITLE
文档-小标题带有大写的英文时，页面左侧导航点击不能跳转。

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos.com#101]

**Comment by yinlianghui** [comment]
标题为全英文或部分英文时都可能有问题。

不能正常跳转的文档：
-  https://beta.steedos.com/docs/developer/jsreport 带有部分英文的标题都不能跳转。
- https://beta.steedos.com/docs/admin/datasource 全英文的标题都不能跳转

能正常跳转的文档：
- https://beta.steedos.com/docs/developer/dashboard 底部报表类型的标题是全英文的，都能正常跳转
- https://www.steedos.cn/docs/deploy/deploy-windows 里面有英文后缀的标题，也有部分英文的标题，都能正常跳转

总结：好像只要标题带有大写的英文字母就不能正常跳转，如果只有小写字母的标题是正常的。
