### ISSUE TITLE
网站新用户注册完成后，跳转到网站后没有用户登陆信息

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos.com#11]
![image](https://user-images.githubusercontent.com/26241897/134606517-cfa8d870-734e-4725-a9b9-baa3232097e2.png)

**Comment by baozhoutao** [comment]
浏览器使用无痕模式

**Comment by baozhoutao** [comment]
无痕模式测试正常

**Comment by baozhoutao** [comment]
尝试重现方式：登录后注销再登录
