### ISSUE TITLE
【官网文档】官网低代码平台文档，访问云服务涉及的网址显示错误

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos.com#161]
操作步骤：
低代码平台-》购买云服务-》访问云服务-》点击文中涉及的网址：https://myurl.steedos.cn/

错误页面：
![image](https://user-images.githubusercontent.com/92509428/172797802-939893aa-dd28-4c18-a7a7-19e009d8b958.png)

**Comment by Flyingliao** [comment]
关联issue： #160
