### ISSUE TITLE
【官网文档】官网低代码平台文档，用户向导中的配置服务地址错误，提示无法访问此页面

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos.com#163]
操作步骤：
低代码平台-》用户向导》下载客户端-》配置服务地址-》打开文中涉及的地址http://localhost:3000/

错误页面：
![image](https://user-images.githubusercontent.com/92509428/172801113-04e2c146-f061-46ca-823a-527ac9271118.png)

**Comment by Flyingliao** [comment]
示例链接，不用处理。
