### ISSUE TITLE
【官网文档】官网低代码平台文档，无代码开发-》页面链接选项卡“[自定义列表视图]超链接打不开

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos.com#170]
操作步骤：
低代码平台-》无代码开发》选项卡-》页面选项卡-》点击[仪表盘开发向导]

错误页面：
![image](https://user-images.githubusercontent.com/92509428/172809497-3e4a7b0a-5aed-4924-9748-79b4cea78a11.png)

**Comment by Flyingliao** [comment]
在 #169 中统一处理了。
