### ISSUE TITLE
【官网文档】官网低代码平台文档，应用集成-》关于驱动包安装中涉及的关于驱动包安装-》点击“ 模板项目的package.json”超链接打不开

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos.com#171]
操作步骤：
低代码平台-》应用集成》数据源-》关于驱动包安装-》点击“ [模板项目的package.json]

错误页面：
![image](https://user-images.githubusercontent.com/92509428/172810338-a829d43d-8bbe-46aa-b0fe-fd353431ceba.png)

**Comment by Flyingliao** [comment]
已处理。
