### ISSUE TITLE
【官网文档】官网低代码平台文档，Node-Red简介-》官网https://Node-Red.org/超链接打不开

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos.com#172]
操作步骤：
低代码平台-》应用集成》Node-Red简介-》点击文中涉及的官网地址：https://node-red.org/。

错误页面：
![image](https://user-images.githubusercontent.com/92509428/172811411-d877829e-2913-4c6f-b9d7-220b81cebdde.png)

**Comment by Flyingliao** [comment]
外网地址，拨VPN 或者开代理访问。
