### ISSUE TITLE
【官网文档】官网低代码平台文档，Node-Red-》支行，官网http://127.0.0.1:1880/ 超链接打不开

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos.com#173]
操作步骤：
低代码平台-》应用集成》Node-Red-》运行-》点击文中涉及的官网地址：http://127.0.0.1:1880/ 

错误页面：
![image](https://user-images.githubusercontent.com/92509428/172811821-e06b0a5d-ba2d-48b9-819d-24db7932a992.png)

**Comment by Flyingliao** [comment]
示例链接，不做处理。
